import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: '#f8fafc',
    flex: 1,
  },
  flowHeader: {
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderBottomColor: '#e2e8f0',
    borderBottomWidth: 1,
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  flowBackButton: {
    alignItems: 'center',
    backgroundColor: '#eefafa',
    borderColor: '#ccefed',
    borderRadius: 999,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  flowHeaderText: { flex: 1 },
  flowTitle: { color: '#004f4c', fontSize: 16, fontWeight: '900' },
  flowSubtitle: { color: '#64748b', fontSize: 11, fontWeight: '700', marginTop: 2 },
  flowHeaderSpacer: { width: 42 },

  // segmented control (used by reviewerCommon.Segmented)
  segmented: {
    backgroundColor: '#f0f3fb',
    borderColor: '#c8d0df',
    borderRadius: 6,
    borderWidth: 1,
    flexDirection: 'row',
    marginTop: 10,
    padding: 2,
  },
  segment: {
    alignItems: 'center',
    borderRadius: 5,
    flex: 1,
    paddingVertical: 10,
  },
  segmentActive: { backgroundColor: '#004f4c' },
  segmentText: { color: '#475569', fontSize: 11, fontWeight: '800' },
  segmentTextActive: { color: '#ffffff' },

  setupContent: { padding: 18, paddingBottom: 28 },
  setupTitle: { color: '#172033', fontSize: 17, fontWeight: '800' },
  setupCopy: { color: '#475569', fontSize: 12, lineHeight: 17, marginTop: 6 },

  sectionTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 8, marginTop: 22 },
  sectionTitle: { color: '#173635', fontSize: 13, fontWeight: '900' },

  fieldLabel: { color: '#172033', fontSize: 11, fontWeight: '800', marginBottom: 7, marginTop: 14 },
  input: {
    backgroundColor: '#ffffff',
    borderColor: '#cbd5e1',
    borderRadius: 6,
    borderWidth: 1,
    color: '#172033',
    fontSize: 13,
    height: 44,
    paddingHorizontal: 12,
  },

  searchField: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#cbd5e1',
    borderRadius: 6,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
  },
  searchInput: { color: '#172033', flex: 1, fontSize: 13, height: 44 },

  suggestionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 9 },
  suggestionChip: {
    backgroundColor: '#eef5fa',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  suggestionChipActive: { backgroundColor: '#d9fbf7' },
  suggestionText: { color: '#64748b', fontSize: 10, fontWeight: '800' },
  suggestionTextActive: { color: '#004f4c' },

  tag: { backgroundColor: '#d9fbf7', borderRadius: 999, paddingHorizontal: 11, paddingVertical: 7 },
  tagText: { color: '#008c84', fontSize: 10, fontWeight: '800' },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 11 },
  addTag: {
    backgroundColor: '#f1f5f9',
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  addTagText: { color: '#94a3b8', fontSize: 10, fontWeight: '800' },

  exportToggle: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 17,
  },
  exportToggleLabel: { color: '#004f4c', fontSize: 12, fontWeight: '900' },
  exportToggleSubtitle: { color: '#64748b', fontSize: 10, marginTop: 3 },

  categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  categoryChip: {
    backgroundColor: '#ffffff',
    borderColor: '#cbd5e1',
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  categoryChipActive: { backgroundColor: '#004f4c', borderColor: '#004f4c' },
  categoryText: { color: '#475569', fontSize: 11, fontWeight: '800' },
  categoryTextActive: { color: '#ffffff' },

  // Question config list
  configList: {
    borderColor: '#cbd5e1',
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 10,
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
  configRow: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderBottomColor: '#e2e8f0',
    borderBottomWidth: 1,
    flexDirection: 'row',
    padding: 12,
  },
  configText: { flex: 1 },
  configTitle: { color: '#172033', fontSize: 12, fontWeight: '900' },
  configSubtitle: { color: '#64748b', fontSize: 10, marginTop: 2 },

  // Stepper
  stepper: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  stepButton: {
    alignItems: 'center',
    backgroundColor: '#f5f3ff',
    borderRadius: 999,
    height: 34,
    justifyContent: 'center',
    width: 34,
    borderColor: '#e9e0ff',
    borderWidth: 1,
  },
  stepSymbol: { color: '#6b46c1', fontSize: 18, fontWeight: '900' },
  stepValue: {
    color: '#173635',
    fontSize: 13,
    fontWeight: '900',
    minWidth: 44,
    textAlign: 'center',
    backgroundColor: '#fbfbff',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderColor: '#eef1ff',
    borderWidth: 1,
  },

  // Guidance + composition
  guidanceCard: { backgroundColor: '#005c58', borderRadius: 10, marginTop: 18, padding: 16 },
  guidanceHeader: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  guidanceTitle: { color: '#dffcf9', fontSize: 14, fontWeight: '900' },
  guidanceText: { color: '#b7e6e2', fontSize: 12, lineHeight: 18, marginTop: 12 },
  guidanceButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#0e8b82',
    borderRadius: 6,
    marginTop: 13,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  guidanceButtonText: { color: '#ffffff', fontSize: 11, fontWeight: '900' },

  compositionLabel: { color: '#172033', fontSize: 12, fontWeight: '900', marginTop: 22 },
  compositionCard: {
    borderColor: '#d3d8ef',
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 8,
    overflow: 'hidden',
  },
  summaryRow: {
    alignItems: 'center',
    backgroundColor: '#f5f7ff',
    borderBottomColor: '#d3d8ef',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 14,
  },
  summaryLabel: { color: '#64748b', fontSize: 12 },
  summaryValue: { color: '#004f4c', fontSize: 12, fontWeight: '900' },

  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#007a48',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginTop: 22,
    paddingVertical: 15,
  },
  primaryButtonText: { color: '#ffffff', fontSize: 12, fontWeight: '900' },
  secondaryButton: {
    alignItems: 'center',
    borderColor: '#004f4c',
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 11,
    paddingVertical: 14,
  },
  secondaryButtonText: { color: '#004f4c', fontSize: 12, fontWeight: '900' },

  materialsHero: {
    backgroundColor: '#ffffff',
    borderColor: '#dbe3f0',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 14,
    padding: 16,
  },
  materialsHeroTitle: { color: '#172033', fontSize: 16, fontWeight: '900' },
  materialsHeroCopy: { color: '#475569', fontSize: 12, lineHeight: 17, marginTop: 6 },
  materialsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 14 },
  materialsActionCard: {
    backgroundColor: '#ffffff',
    borderColor: '#dbe3f0',
    borderRadius: 14,
    borderWidth: 1,
    flexBasis: '48%',
    minHeight: 120,
    padding: 14,
  },
  materialsActionCardAccent: {
    backgroundColor: '#004f4c',
    borderColor: '#004f4c',
  },
  materialsActionIcon: {
    alignItems: 'center',
    backgroundColor: '#eefafa',
    borderRadius: 999,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  materialsActionIconAccent: { backgroundColor: 'rgba(255,255,255,0.12)' },
  materialsActionTitle: { color: '#172033', fontSize: 13, fontWeight: '900', marginTop: 12 },
  materialsActionTitleAccent: { color: '#ffffff' },
  materialsActionCopy: { color: '#64748b', fontSize: 11, lineHeight: 16, marginTop: 4 },
  materialsActionCopyAccent: { color: '#d9fbf7' },

  linkCard: {
    backgroundColor: '#ffffff',
    borderColor: '#dbe3f0',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 16,
    padding: 14,
  },
  linkActionsRow: { flexDirection: 'row', gap: 10, marginTop: 12 },
  linkButton: {
    alignItems: 'center',
    backgroundColor: '#004f4c',
    borderRadius: 10,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  linkButtonSecondary: { backgroundColor: '#eef5fa' },
  linkButtonText: { color: '#ffffff', fontSize: 12, fontWeight: '900' },
  linkButtonTextSecondary: { color: '#172033' },
  busyRow: { alignItems: 'center', flexDirection: 'row', gap: 8, marginTop: 12 },
  busyText: { color: '#64748b', fontSize: 11, fontWeight: '700' },

  materialsPreviewCard: {
    backgroundColor: '#ffffff',
    borderColor: '#dbe3f0',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 16,
    padding: 14,
  },
  materialsPreviewHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  materialsPreviewCount: { color: '#64748b', fontSize: 11, fontWeight: '700' },
  materialsPreviewEmpty: {
    backgroundColor: '#f8fafc',
    borderColor: '#e2e8f0',
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 12,
    padding: 14,
  },
  materialsPreviewEmptyText: { color: '#64748b', fontSize: 11, lineHeight: 16 },
  materialsPreviewList: { gap: 10, marginTop: 12 },
  materialsSwipeWrap: {
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
  },
  materialsDeleteAction: {
    alignItems: 'center',
    backgroundColor: '#dc2626',
    bottom: 0,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    paddingHorizontal: 14,
    position: 'absolute',
    right: 0,
    top: 0,
    width: 100,
  },
  materialsDeleteText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '900',
  },
  materialsPreviewItem: {
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderColor: '#e2e8f0',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
  materialsPreviewThumb: {
    backgroundColor: '#e2e8f0',
    borderRadius: 10,
    height: 58,
    width: 58,
  },
  materialsPreviewIconWrap: {
    alignItems: 'center',
    backgroundColor: '#eefafa',
    borderRadius: 10,
    height: 58,
    justifyContent: 'center',
    width: 58,
  },
  materialsPreviewBody: { flex: 1 },
  materialsPreviewTitle: { color: '#172033', fontSize: 12, fontWeight: '900' },
  materialsPreviewMeta: { color: '#64748b', fontSize: 10, lineHeight: 14, marginTop: 2 },
  materialsPreviewUrl: { color: '#008c84', fontSize: 10, marginTop: 4 },
  materialsPreviewStatus: {
    alignSelf: 'flex-start',
    backgroundColor: '#eef5fa',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  materialsPreviewStatusSaved: { backgroundColor: '#d9fbf7' },
  materialsPreviewStatusUploading: { backgroundColor: '#fef3c7' },
  materialsPreviewStatusFailed: { backgroundColor: '#fee2e2' },
  materialsPreviewStatusText: { color: '#004f4c', fontSize: 9, fontWeight: '800' },
  materialsPreviewStatusTextFailed: { color: '#b91c1c' },

  // Extraction screen small bits
  extractionContent: { padding: 18, paddingBottom: 28 },
  scanHero: { alignItems: 'center', paddingTop: 20 },
  scanRing: {
    alignItems: 'center',
    borderColor: '#b8f3d3',
    borderRadius: 999,
    borderWidth: 4,
    height: 104,
    justifyContent: 'center',
    width: 104,
  },
  scanIcon: {
    alignItems: 'center',
    backgroundColor: '#006f6a',
    borderRadius: 18,
    height: 66,
    justifyContent: 'center',
    width: 66,
  },
  scanTitle: { color: '#004f4c', fontSize: 21, fontWeight: '900', marginTop: 14 },
  scanCopy: { color: '#64748b', fontSize: 11, marginTop: 5, textAlign: 'center' },
  statusGrid: { flexDirection: 'row', gap: 10, marginTop: 26 },
  statusTile: {
    backgroundColor: '#ffffff',
    borderLeftColor: '#42d8e7',
    borderLeftWidth: 3,
    flex: 1,
    padding: 12,
  },
  statusTileActive: { borderLeftColor: '#00d382' },
  statusLabel: { color: '#94a3b8', fontSize: 9, fontWeight: '800' },
  statusValue: { color: '#004f4c', fontSize: 11, fontWeight: '900', marginTop: 3 },
  extractedCard: { backgroundColor: '#ffffff', borderRadius: 9, marginTop: 10, padding: 14 },
  extractedTop: { flexDirection: 'row', justifyContent: 'space-between' },
  extractedLabel: { color: '#94a3b8', fontSize: 9, fontWeight: '900' },
  characterCount: { color: '#94a3b8', fontSize: 9 },
  extractedText: { color: '#334155', fontSize: 12, lineHeight: 18, marginTop: 12 },
  detectedLabel: { color: '#94a3b8', fontSize: 11, fontWeight: '800', marginTop: 18 },
  detectedCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 9,
    marginTop: 8,
    padding: 14,
  },
  detectedText: { color: '#004f4c', fontSize: 13, fontWeight: '900' },
});

export default {} as any;
