import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: '#f6fbff',
    flex: 1,
  },
  keyboardArea: {
    flex: 1,
  },
  header: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderBottomColor: '#dbe8ee',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  headerButton: {
    alignItems: 'center',
    backgroundColor: '#eefafa',
    borderRadius: 999,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 7,
  },
  headerMiniButton: {
    alignItems: 'center',
    backgroundColor: '#eefafa',
    borderRadius: 999,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  headerIdentity: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 10,
  },
  headerAvatar: {
    height: 42,
    width: 72,
  },
  headerCopy: {
    flex: 1,
  },
  headerTitle: {
    color: '#004f4c',
    fontSize: 17,
    fontWeight: '900',
  },
  headerTitleInput: {
    backgroundColor: '#f4fbfb',
    borderColor: '#d8e8e9',
    borderRadius: 10,
    borderWidth: 1,
    color: '#004f4c',
    fontSize: 16,
    fontWeight: '900',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  statusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginTop: 2,
  },
  statusDot: {
    backgroundColor: '#12b76a',
    borderRadius: 999,
    height: 7,
    width: 7,
  },
  headerSubtitle: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '800',
  },
  flowBar: {
    alignItems: 'center',
    backgroundColor: '#e9fbfb',
    borderBottomColor: '#d5eeee',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  flowIcon: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 999,
    height: 31,
    justifyContent: 'center',
    width: 31,
  },
  flowCopy: {
    flex: 1,
  },
  flowTitle: {
    color: '#004f4c',
    fontSize: 12,
    fontWeight: '900',
  },
  flowText: {
    color: '#64748b',
    fontSize: 10,
    fontWeight: '800',
    marginTop: 1,
  },
  chatContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 18,
  },
  loadingHistoryCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#dbe8ee',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
    padding: 14,
  },
  loadingHistoryText: {
    color: '#004f4c',
    fontSize: 12,
    fontWeight: '900',
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#dbe8ee',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 12,
    padding: 18,
  },
  emptyLogo: {
    height: 84,
    width: 148,
  },
  emptyTitle: {
    color: '#004f4c',
    fontSize: 19,
    fontWeight: '900',
    marginTop: 8,
    textAlign: 'center',
  },
  emptyText: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 6,
    textAlign: 'center',
  },
  promptRow: {
    gap: 8,
    paddingVertical: 8,
  },
  promptChip: {
    backgroundColor: '#eefafa',
    borderColor: '#d0eeee',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  promptText: {
    color: '#004f4c',
    fontSize: 11,
    fontWeight: '900',
  },
  mentorRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  avatarShell: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#dbe8ee',
    borderRadius: 999,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 44,
  },
  messageAvatar: {
    height: 38,
    width: 46,
  },
  mentorColumn: {
    flex: 1,
  },
  mentorBubble: {
    backgroundColor: '#ffffff',
    borderColor: '#dbe8ee',
    borderRadius: 12,
    borderTopLeftRadius: 4,
    borderWidth: 1,
    padding: 14,
    shadowColor: '#0b2440',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.04,
    shadowRadius: 14,
  },
  mentorBubbleSuccess: {
    backgroundColor: '#ecfdf5',
    borderColor: '#bbf7d0',
  },
  mentorBubbleWarning: {
    backgroundColor: '#fff7ed',
    borderColor: '#fed7aa',
  },
  mentorText: {
    color: '#223044',
    fontSize: 14,
    lineHeight: 21,
  },
  mentorMeta: {
    color: '#94a3b8',
    fontSize: 10,
    fontWeight: '800',
    marginTop: 6,
  },
  userGroup: {
    alignItems: 'flex-end',
    marginBottom: 18,
    paddingLeft: 66,
  },
  userBubble: {
    backgroundColor: '#004f4c',
    borderRadius: 12,
    borderTopRightRadius: 4,
    padding: 14,
  },
  userText: {
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 21,
  },
  userMeta: {
    color: '#94a3b8',
    fontSize: 10,
    fontWeight: '800',
    marginTop: 6,
  },
  typingBubble: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#dbe8ee',
    borderRadius: 12,
    borderTopLeftRadius: 4,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  typingText: {
    color: '#004f4c',
    fontSize: 12,
    fontWeight: '900',
  },
  composerWrap: {
    backgroundColor: '#ffffff',
    borderTopColor: '#dbe8ee',
    borderTopWidth: 1,
    bottom: 0,
    left: 0,
    paddingHorizontal: 14,
    paddingTop: 10,
    position: 'absolute',
    right: 0,
  },
  composerRow: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: 10,
  },
  attachmentPreview: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#e6eef0',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
    padding: 10,
  },
  attachmentInfo: {
    flex: 1,
  },
  attachmentPreviewTitle: {
    color: '#06383a',
    fontSize: 14,
    fontWeight: '700',
  },
  attachmentPreviewSubtitle: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 2,
  },
  attachmentRemove: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 6,
  },
  attachButton: {
    alignItems: 'center',
    backgroundColor: '#eefafa',
    borderColor: '#d0eeee',
    borderRadius: 999,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  attachButtonDisabled: {
    opacity: 0.58,
  },
  composer: {
    backgroundColor: '#f4fbfb',
    borderColor: '#d8e8e9',
    borderRadius: 22,
    borderWidth: 1,
    color: '#223044',
    flex: 1,
    fontSize: 14,
    maxHeight: 118,
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  sendButton: {
    alignItems: 'center',
    backgroundColor: '#004f4c',
    borderRadius: 999,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  sendButtonDisabled: {
    backgroundColor: '#9bb7b5',
  },
  errorText: {
    color: '#b42318',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 7,
    paddingHorizontal: 2,
  },
  reviewersCta: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#eefafa',
    borderColor: '#d0eeee',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    marginBottom: 8,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  reviewersCtaText: {
    color: '#004f4c',
    fontSize: 11,
    fontWeight: '900',
  },
  attachmentCard: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#ffffff',
    borderColor: '#dbe8ee',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
    maxWidth: '96%',
    padding: 10,
  },
  attachmentIcon: {
    alignItems: 'center',
    backgroundColor: '#eefafa',
    borderRadius: 10,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  attachmentBody: {
    flex: 1,
    minWidth: 120,
  },
  attachmentTitle: {
    color: '#172033',
    fontSize: 12,
    fontWeight: '900',
  },
  attachmentMeta: {
    color: '#64748b',
    fontSize: 10,
    fontWeight: '800',
    marginTop: 2,
  },
  attachmentLibrary: {
    color: '#007a80',
    fontSize: 10,
    fontWeight: '900',
    marginTop: 3,
  },
  attachmentStatus: {
    backgroundColor: '#fef3c7',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  attachmentStatusReady: {
    backgroundColor: '#d9fbf7',
  },
  attachmentStatusFailed: {
    backgroundColor: '#fee2e2',
  },
  attachmentStatusText: {
    color: '#92400e',
    fontSize: 9,
    fontWeight: '900',
  },
  attachmentStatusTextFailed: {
    color: '#b91c1c',
  },
  historyBackdrop: {
    backgroundColor: 'rgba(15, 23, 42, 0.42)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  historySheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    maxHeight: '84%',
    paddingBottom: 20,
    paddingHorizontal: 16,
    paddingTop: 18,
  },
  historyHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  historyEyebrow: {
    color: '#007a80',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  historyTitle: {
    color: '#004f4c',
    fontSize: 22,
    fontWeight: '900',
    marginTop: 2,
  },
  historyClose: {
    alignItems: 'center',
    backgroundColor: '#eefafa',
    borderRadius: 999,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  historyActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
    marginTop: 14,
  },
  historyNew: {
    alignItems: 'center',
    backgroundColor: '#004f4c',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: 13,
    paddingVertical: 11,
  },
  historyNewText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '900',
  },
  historySearch: {
    backgroundColor: '#f4fbfb',
    borderColor: '#d8e8e9',
    borderRadius: 999,
    borderWidth: 1,
    color: '#172033',
    flex: 1,
    fontSize: 12,
    minHeight: 42,
    paddingHorizontal: 14,
  },
  historyError: {
    color: '#b42318',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 10,
  },
  historyEmpty: {
    alignItems: 'center',
    borderColor: '#dbe8ee',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 14,
    padding: 20,
  },
  historyEmptyTitle: {
    color: '#004f4c',
    fontSize: 16,
    fontWeight: '900',
    marginTop: 8,
  },
  historyEmptyText: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
    textAlign: 'center',
  },
  historyList: {
    gap: 10,
    paddingTop: 14,
  },
  historyItem: {
    alignItems: 'center',
    backgroundColor: '#f8fbfd',
    borderColor: '#dbe8ee',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    padding: 10,
  },
  historyItemActive: {
    backgroundColor: '#eefafa',
    borderColor: '#9be7e1',
  },
  historyItemMain: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 10,
  },
  historyItemIcon: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  historyItemBody: {
    flex: 1,
  },
  historyItemTitle: {
    color: '#172033',
    fontSize: 13,
    fontWeight: '900',
  },
  historyTitleInput: {
    backgroundColor: '#f4fbfb',
    borderColor: '#d8e8e9',
    borderRadius: 10,
    borderWidth: 1,
    color: '#172033',
    fontSize: 13,
    fontWeight: '900',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  historyItemPreview: {
    color: '#64748b',
    fontSize: 11,
    lineHeight: 15,
    marginTop: 3,
  },
  historyItemMeta: {
    color: '#007a80',
    fontSize: 10,
    fontWeight: '900',
    marginTop: 5,
  },
  historyItemActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  historyDelete: {
    alignItems: 'center',
    borderRadius: 999,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
});
